# DB 연결 정보 (MariaDB 기준)
spring.datasource.url=jdbc:mariadb://yeonghun.com:3306/admin_bsh
spring.datasource.username=${QUIZ2025_USERNAME}
spring.datasource.password=${QUIZ2025_PASSWORD}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# Redis 설정
spring.data.redis.host=localhost
spring.data.redis.port=6380

# JWT 설정 (개발용 키)
jwt.secret=localSecretKey1234567890!@#devsdjldfj3393!ffdlos
jwt.access-token-expiration-time=3600000
jwt.refresh-token-expiration-time=86400000
jwt.token-prefix=Bearer
jwt.header-string=Authorization

