# DB 연결 정보 (MariaDB 기준)
spring.datasource.url=jdbc:mariadb://localhost:3306/quiz2025
spring.datasource.username=admin
spring.datasource.password=1111
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# Redis 설정
spring.data.redis.host=localhost
spring.data.redis.port=6380

# JWT 설정 (개발용 키)
jwt.secret=prodSecretKey1234567890!@#prod
jwt.access-token-expiration-time=3600000
jwt.refresh-token-expiration-time=86400000
jwt.token-prefix=Bearer
jwt.header-string=Authorization

